filebeat.inputs:
  - type: filestream
    paths:
      - /var/lib/docker/containers/*/*.log
    parsers:
      - ndjson:
          target: "docker"
          message_key: "log"

processors:
  - add_docker_metadata: ~

output.elasticsearch:
  hosts: ["http://peaktime-elasticsearch:9200"]