name: Feature
description: 새로운 기능 개발 요청
title: "[feat] "
labels: ["feature"]
assignees: []

body:
  - type: textarea
    attributes:
      label: 기능 요약
      description: 무엇을, 왜 하는지 한두 문장으로 작성해주세요.
      placeholder: ex) 사용자 프로필 수정 기능 추가
    validations:
      required: true

  - type: textarea
    attributes:
      label: 작업 항목
      description: 필요한 작업이 있다면 간단히 적어주세요. (선택)
      placeholder: |
        - [ ] 요구사항 정리
        - [ ] API 설계/변경
        - [ ] DB 스키마/마이그레이션
        - [ ] 테스트(단위/통합)
        - [ ] 문서(Spring REST Docs/README)
    validations:
      required: false

  - type: textarea
    attributes:
      label: 참고
      description: 관련 문서/스펙, API 문서(Spring REST Docs), ERD, 와이어프레임 링크(필요 시) 등 (선택)
    validations:
      required: false